version: 2
registries:
  nuget-feed-nuget-pkg-github-com-ashleighadams-index-json:
    type: nuget-feed
    url: https://nuget.pkg.github.com/AshleighAdams/index.json
    username: "${{secrets.NUGET_FEED_NUGET_PKG_GITHUB_COM_ASHLEIGHADAMS_INDEX_JSON_USERNAME}}"
    password: "${{secrets.NUGET_FEED_NUGET_PKG_GITHUB_COM_ASHLEIGHADAMS_INDEX_JSON_PASSWORD}}"
  public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  registries:
  - nuget-feed-nuget-pkg-github-com-ashleighadams-index-json
  - public
  groups:
    all:
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]